
defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: 
  pool: 5
  username: <%= ENV["DB_USER"] || "foosrails" %>
  password: <%= ENV["DB_PASSWORD"] || "foosrails" %>
  socket: <%= ENV["DB_SOCKET"] || "/tmp/mysql.sock" %>


development:
  <<: *defaults


test:
  <<: *defaults
  database: <%= ENV["DB_NAME"] || "foosrails" %>_test

production:
  <<: *defaults